# NumPy Notes

## Basics

In NumPy:
* All elements in the array have the same type
* dimensions are called "axes"
* The number of axes is the "rank"
* Numpy's array class is called "ndarray" which is aliased as "array".

In [37]:
import numpy as np
# This makes jupyter display output from every line of code rather than just the last one.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [31]:
a[0,2,2] 
a[1,1,1]
a[2,0,0]

8

13

18

In [32]:
a.shape

(3, 3, 3)

In [33]:
# You can specify the data type with "dtype"
np.ones((2,3), dtype=np.float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [60]:
# You can construct an array from a function
a = np.fromfunction(lambda z,y,x: (x+1)*(y+1)*(z+1), (4,4,4), dtype=float)
a

array([[[  1.,   2.,   3.,   4.],
        [  2.,   4.,   6.,   8.],
        [  3.,   6.,   9.,  12.],
        [  4.,   8.,  12.,  16.]],

       [[  2.,   4.,   6.,   8.],
        [  4.,   8.,  12.,  16.],
        [  6.,  12.,  18.,  24.],
        [  8.,  16.,  24.,  32.]],

       [[  3.,   6.,   9.,  12.],
        [  6.,  12.,  18.,  24.],
        [  9.,  18.,  27.,  36.],
        [ 12.,  24.,  36.,  48.]],

       [[  4.,   8.,  12.,  16.],
        [  8.,  16.,  24.,  32.],
        [ 12.,  24.,  36.,  48.],
        [ 16.,  32.,  48.,  64.]]])

## Slicing

In [50]:
# slicing
# ... is equivalent to as many colons as needed to complete the indexing tuple
a[1, ...]
a[1, ..., 1] # same as a[1, :, 1], which means the first row from the set of all rows where z=1 

array([[  2.,   4.,   6.,   8.],
       [  4.,   8.,  12.,  16.],
       [  6.,  12.,  18.,  24.],
       [  8.,  16.,  24.,  32.]])

array([  4.,   8.,  12.,  16.])

In [52]:
# More complicated examples
a[:, 0:3, 0:2]

array([[[  1.,   2.],
        [  2.,   4.],
        [  3.,   6.]],

       [[  2.,   4.],
        [  4.,   8.],
        [  6.,  12.]],

       [[  3.,   6.],
        [  6.,  12.],
        [  9.,  18.]],

       [[  4.,   8.],
        [  8.,  16.],
        [ 12.,  24.]]])

In [62]:
# E.g. multiply the top left and bottom right corner of a matrix by 2
a = np.ones((8,8))
a[4:,4:] *= 2
a[0:4, 0:4] *= 2
a

array([[ 2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.]])

## Iteration

In [66]:
# Iterate over the first axis
for row in a:
    print row

array([[ 2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.]])

In [73]:
# Iterator over the flattened data
for element in a[0:2].flat:
    print(element)

2.0
2.0
2.0
2.0
1.0
1.0
1.0
1.0
2.0
2.0
2.0
2.0
1.0
1.0
1.0
1.0


In [74]:
# ravel also flattens the array, but returns another array rather than an iterator
a.ravel()

array([ 2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  1.,
        1.,  1.,  1.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,
        2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,
        2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,
        2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.])

## Stacking

In [76]:
# arrays can be stacked either horizontally or vertically.
ones = np.ones((4,4))
twos = np.ones((4,4)) * 2

np.vstack((ones, twos))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.]])

In [77]:
np.hstack((ones, twos))

array([[ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.]])

In [79]:
# Different sizes fails
np.hstack((np.zeros((2,2)), np.ones((3,3))))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

## Other Things
* 'Views' allow multiple arrays to point to the same data, use the "view()" method
* Deep copies can be performed with the "copy()" method